<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Bing.Utils.DateTime</AssemblyName>
		<PackageId>Bing.Utils.DateTime</PackageId>
		<Description>Bing.Utils.DateTime是Bing应用框架的时间操作类库。</Description>
	</PropertyGroup>

	<Import Project="..\..\common.props" />

	<ItemGroup>
		<ProjectReference Include="..\Bing.Utils\Bing.Utils.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NodaTime" Version="3.1.2" />
	</ItemGroup>

</Project>
