<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Bing.Utils.Drawing.ImageSharp</AssemblyName>
		<PackageId>Bing.Utils.Drawing.ImageSharp</PackageId>
		<Description>Bing.Utils.Drawing.ImageSharp是Bing应用框架的图片操作类库。基于 SixLabors.ImageSharp 封装的类库</Description>
	</PropertyGroup>

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SixLabors.ImageSharp" Version="2.1.11" />
	</ItemGroup>

  <ItemGroup><ProjectReference Include="../Bing.Utils.Drawing.Shared/Bing.Utils.Drawing.Shared.csproj" /></ItemGroup>
  <ItemGroup><PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0" /><PackageReference Include="SixLabors.Fonts" Version="1.0.0" /></ItemGroup>
</Project>
