<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Bing.Utils.Drawing.ImageSharp</AssemblyName>
		<PackageId>Bing.Utils.Drawing.ImageSharp</PackageId>
		<Description>Bing.Utils.Drawing.ImageSharp是Bing应用框架的图片操作类库。基于 SixLabors.ImageSharp 封装的类库</Description>
	</PropertyGroup>

	<Import Project="..\..\common.props" />

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\DrawingCompatibilityHelper.cs" Link="Bing\Drawing\Internal\DrawingCompatibilityHelper.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\CaptchaCodeGenerator.cs" Link="Bing\Drawing\Internal\CaptchaCodeGenerator.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\GrayImageBuffer.cs" Link="Bing\Drawing\Internal\GrayImageBuffer.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\BinaryImageProcessor.cs" Link="Bing\Drawing\Internal\BinaryImageProcessor.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\NoiseReductionProcessor.cs" Link="Bing\Drawing\Internal\NoiseReductionProcessor.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\ConnectedComponentProcessor.cs" Link="Bing\Drawing\Internal\ConnectedComponentProcessor.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\ProjectionProcessor.cs" Link="Bing\Drawing\Internal\ProjectionProcessor.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\IcoContainerWriter.cs" Link="Bing\Drawing\Internal\IcoContainerWriter.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\TwistGeometryProcessor.cs" Link="Bing\Drawing\Internal\TwistGeometryProcessor.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\ErosionEffectHelper.cs" Link="Bing\Drawing\Internal\ErosionEffectHelper.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\Internal\ImageGeometryHelper.cs" Link="Bing\Drawing\Internal\ImageGeometryHelper.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\ThumbnailMode.cs" Link="Bing\Drawing\ThumbnailMode.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\ColorMatrices.cs" Link="Bing\Drawing\ColorMatrices.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\CaptchaType.cs" Link="Bing\Drawing\CaptchaType.cs" />
	  <Compile Include="..\Bing.Utils.Drawing.Shared\Bing\Drawing\CaptchaOptions.cs" Link="Bing\Drawing\CaptchaOptions.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SixLabors.ImageSharp" Version="2.1.11" />
	</ItemGroup>

</Project>
