<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Bing.Utils.Extra._shared.props" />

  <Import Project="..\..\common.props" />

  <ItemGroup>
    <None Include="..\..\asset\emoji\LICENSE.unicode.txt" Pack="true" PackagePath="licenses/" />
    <None Include="..\..\asset\emoji\LICENSE.gemoji.txt" Pack="true" PackagePath="licenses/" />
    <None Include="..\..\asset\emoji\README.md" Pack="true" PackagePath="licenses/emoji-sources.md" />
  </ItemGroup>

</Project>
